# Generated by Django 5.2.5 on 2025-08-13 10:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QdrantDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên Database')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Qdrant Database',
                'verbose_name_plural': 'Qdrant Databases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QdrantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qdrant_id', models.CharField(max_length=255, verbose_name='Qdrant ID')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('link_source', models.URLField(blank=True, null=True, verbose_name='Nguồn liên kết')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên file')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='qdrant_manager.qdrantdatabase', verbose_name='Database')),
            ],
            options={
                'verbose_name': 'Qdrant Document',
                'verbose_name_plural': 'Qdrant Documents',
                'ordering': ['-created_at'],
                'unique_together': {('database', 'qdrant_id')},
            },
        ),
    ]
