# Generated by Django 5.2.5 on 2025-08-14 02:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdrant_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QdrantCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên collection trên Qdrant server', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả về collection')),
                ('vector_size', models.PositiveIntegerField(help_text='Kích thước vector (số chiều)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('distance_metric', models.CharField(choices=[('cosine', 'Cosine'), ('euclidean', 'Euclidean'), ('dot', 'Dot Product')], default='cosine', help_text='Độ đo khoảng cách sử dụng', max_length=20)),
                ('qdrant_synced', models.BooleanField(default=False, help_text='Đã đồng bộ với Qdrant server')),
                ('points_count', models.PositiveIntegerField(default=0, help_text='Số lượng points trong collection')),
                ('vectors_count', models.PositiveIntegerField(default=0, help_text='Số lượng vectors trong collection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qdrant Collection',
                'verbose_name_plural': 'Qdrant Collections',
                'db_table': 'qdrant_collection',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='qdrantdatabase',
            options={'verbose_name': 'Qdrant Database (Deprecated)', 'verbose_name_plural': 'Qdrant Databases (Deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='qdrantdocument',
            options={'verbose_name': 'Qdrant Document (Deprecated)', 'verbose_name_plural': 'Qdrant Documents (Deprecated)'},
        ),
        migrations.RemoveField(
            model_name='qdrantdocument',
            name='link_source',
        ),
        migrations.AlterField(
            model_name='qdrantdatabase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qdrantdatabase',
            name='description',
            field=models.TextField(blank=True, help_text='Mô tả về database'),
        ),
        migrations.AlterField(
            model_name='qdrantdatabase',
            name='name',
            field=models.CharField(help_text='Tên database', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='qdrantdatabase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qdrantdocument',
            name='content',
            field=models.TextField(help_text='Nội dung document'),
        ),
        migrations.AlterField(
            model_name='qdrantdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qdrantdocument',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='qdrant_manager.qdrantdatabase'),
        ),
        migrations.AlterField(
            model_name='qdrantdocument',
            name='file_name',
            field=models.CharField(blank=True, help_text='Tên file gốc', max_length=255),
        ),
        migrations.AlterField(
            model_name='qdrantdocument',
            name='qdrant_id',
            field=models.CharField(help_text='ID trong Qdrant', max_length=200),
        ),
        migrations.AlterField(
            model_name='qdrantdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='qdrantdatabase',
            table='qdrant_database',
        ),
        migrations.AlterModelTable(
            name='qdrantdocument',
            table='qdrant_document',
        ),
        migrations.CreateModel(
            name='QdrantPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.CharField(help_text='ID của point trong Qdrant (UUID, số, hoặc string)', max_length=200)),
                ('content', models.TextField(help_text='Nội dung chính của point (sẽ được vector hóa)')),
                ('title', models.CharField(blank=True, help_text='Tiêu đề hoặc tên ngắn gọn', max_length=500)),
                ('source', models.URLField(blank=True, help_text='URL nguồn của nội dung')),
                ('file_name', models.CharField(blank=True, help_text='Tên file nguồn', max_length=255)),
                ('category', models.CharField(blank=True, help_text='Danh mục phân loại', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Danh sách tags')),
                ('vector_data', models.JSONField(blank=True, default=list, help_text='Dữ liệu vector (array of floats)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata bổ sung dưới dạng JSON')),
                ('qdrant_synced', models.BooleanField(default=False, help_text='Đã đồng bộ với Qdrant server')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(help_text='Collection chứa point này', on_delete=django.db.models.deletion.CASCADE, related_name='points', to='qdrant_manager.qdrantcollection')),
            ],
            options={
                'verbose_name': 'Qdrant Point',
                'verbose_name_plural': 'Qdrant Points',
                'db_table': 'qdrant_point',
                'ordering': ['-created_at'],
                'unique_together': {('collection', 'point_id')},
            },
        ),
    ]
