# Generated by Django 5.2.5 on 2025-08-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdrant_manager', '0002_add_new_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='qdrantcollection',
            name='file_name',
            field=models.CharField(blank=True, help_text='Tên file đầu tiên trong collection', max_length=255),
        ),
    ]
