# Generated by Django 5.2.5 on 2025-08-14 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdrant_manager', '0003_qdrantcollection_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qdrantcollection',
            name='file_name',
        ),
    ]
